@startuml proyecto_juego

class Clase {
    - nombre: str
    - descripcion: str
    - estadisticas: float
}

class Item {
    - nombre: str
    - tipo: str
    - efecto: float
}

class Personaje {
    - nombre: str
    - vida: float
    - daño: float
    - armadura: float
    - raza: Raza
    - clase: Clase
    - mana: float
    - nivel: int
    + atacar(): void 
    + recibir_daño(): void
    + defender(): void
    + usar_item(item: Item): void
    + usar_habilidad_especial(): void
}

class Protagonista {
    - experiencia: float
    + subir_nivel(): void
}

class Enemigo {
    - es_jefe: boolean
}

class Lugar {
    - nombre: str
}

class Juego {
    - lista_protagonista: List<Protagonista>
    - lista_enemigo: List<Enemigo>
    - lista_lugar: List<Lugar>
    + iniciar(): void
    + avanzar_lugar(): void 
    + guardar_partida():void
    + cargar_partida(): void 
}

class Combate{
    +iniciar_combate():
}


Personaje "1" -- "0..*" Item

Personaje --> Protagonista
Personaje --> Enemigo
Personaje "1" -- "1" Clase
Lugar "1" -- "1..*" Enemigo 
Juego "1" -- "1..*" Protagonista
Juego "1" -- "1..*" Enemigo
Juego "1" -- "1..*" Lugar