@startuml proyecto_juego

class Raza {
    - descripcion: String
}

class Humano {
    + determinacion(): Void
}

class NiñoBosque {
    + magiaNatural(): Void
}

class Gigante {
    + fuerzaBruta(): Void
}

class Clase {
    - descripcion: String
    - daño: Float
    - armadura: Float
    - vida: Float
}

class Arquero {
    + tiroCertero(): Void
}

class Guerrero {
    + golpeHelado(): Void
}

class MagoFuego {
    - mana: Float
    + fuegoDragon(): Void
}

class Item {
    - nombre: String
    - tipo: String
    - efecto: Float
}

class Personaje {
    - nombre: String
    - vida: Float
    - daño: Float
    - armadura: Float
    - nivel: Integer
    + atacar(): Void 
    + recibirDaño(): Void
    + defender(): Void
    + usarItem(item: Item): Void
    + usarHabilidadEspecial(): Void
}

class Protagonista {
    - experiencia: Float
    + subirNivel(): Void
}

class Enemigo {
    - esJefe: Boolean
}

class Lugar {
    - nombre: String
    - descripcion: String
}

class Juego {
    + personaje: List<Personaje>
    + lugar: List<Lugar>
    + iniciarBatalla(): Void
    + avanzarLugar(): Void
    + guardarPartida(): Void
    + cargarPartida(): Void
}

Personaje "1" -- "0..*" Item

Personaje <|-- Protagonista
Personaje <|-- Enemigo
Personaje "1" -- "1" Raza
Personaje "1" -- "1" Clase

Clase <|-- Arquero
Clase <|-- Guerrero
Clase <|-- MagoFuego
Raza <|-- Humano
Raza <|-- NiñoBosque
Raza <|-- Gigante

Juego *-- Personaje
Juego *-- Lugar
